# Generated by Django 2.2 on 2020-08-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_empleado_hoja_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre completo'),
        ),
    ]
